name: Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { submodules: recursive }

      - name: Build
        run: |
          rm -f release/* || true
          zip -x "release/" -x "release/.*" -9 -r release/pong.love *

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/pong.love"
          allowUpdates: true
